# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: askpass.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'askpass.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raskpass.proto\x12\x07\x61skpass\".\n\x0ePasswordPrompt\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0c\n\x04\x65\x63ho\x18\x02 \x01(\x08\"4\n\rPasswordReply\x12\x10\n\x08password\x18\x01 \x01(\t\x12\x11\n\tcancelled\x18\x02 \x01(\x08\x32M\n\x07\x41skPass\x12\x42\n\x0fRequestPassword\x12\x17.askpass.PasswordPrompt\x1a\x16.askpass.PasswordReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'askpass_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PASSWORDPROMPT']._serialized_start=26
  _globals['_PASSWORDPROMPT']._serialized_end=72
  _globals['_PASSWORDREPLY']._serialized_start=74
  _globals['_PASSWORDREPLY']._serialized_end=126
  _globals['_ASKPASS']._serialized_start=128
  _globals['_ASKPASS']._serialized_end=205
# @@protoc_insertion_point(module_scope)
