# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lazysync.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lazysync.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elazysync.proto\x12\x08lazysync\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1e\n\x0eGetPathRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1b\n\x0bStatRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"@\n\x0cStatResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12 \n\x04info\x18\x02 \x01(\x0b\x32\x12.lazysync.FileInfo\"?\n\x0fReadFileRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x04\x12\x0e\n\x06length\x18\x03 \x01(\x04\":\n\rReadFileChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0e\n\x06offset\x18\x02 \x01(\x04\x12\x0b\n\x03\x65of\x18\x03 \x01(\x08\"I\n\x0eWriteFileChunk\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x0b\n\x03\x65of\x18\x04 \x01(\x08\"*\n\x11WriteFileResponse\x12\x15\n\rbytes_written\x18\x01 \x01(\x04\"w\n\x08\x46ileInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tfile_type\x18\x02 \x01(\t\x12\x13\n\x0bpermissions\x18\x03 \x01(\t\x12\x15\n\rabsolute_path\x18\x04 \x01(\t\x12\x10\n\x08modified\x18\x05 \x01(\t\x12\x0c\n\x04size\x18\x06 \x01(\x04\"H\n\nDirEntries\x12\x15\n\rabsolute_path\x18\x01 \x01(\t\x12#\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x12.lazysync.FileInfo\"F\n\x0fGetPathResponse\x12\x0c\n\x04path\x18\x01 \x01(\t\x12%\n\x07\x65ntries\x18\x02 \x03(\x0b\x32\x14.lazysync.DirEntries2\xc6\x02\n\x08LazySync\x12;\n\x06Health\x12\x17.lazysync.HealthRequest\x1a\x18.lazysync.HealthResponse\x12>\n\x07GetPath\x12\x18.lazysync.GetPathRequest\x1a\x19.lazysync.GetPathResponse\x12\x35\n\x04Stat\x12\x15.lazysync.StatRequest\x1a\x16.lazysync.StatResponse\x12@\n\x08ReadFile\x12\x19.lazysync.ReadFileRequest\x1a\x17.lazysync.ReadFileChunk0\x01\x12\x44\n\tWriteFile\x12\x18.lazysync.WriteFileChunk\x1a\x1b.lazysync.WriteFileResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lazysync_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=28
  _globals['_HEALTHREQUEST']._serialized_end=43
  _globals['_HEALTHRESPONSE']._serialized_start=45
  _globals['_HEALTHRESPONSE']._serialized_end=77
  _globals['_GETPATHREQUEST']._serialized_start=79
  _globals['_GETPATHREQUEST']._serialized_end=109
  _globals['_STATREQUEST']._serialized_start=111
  _globals['_STATREQUEST']._serialized_end=138
  _globals['_STATRESPONSE']._serialized_start=140
  _globals['_STATRESPONSE']._serialized_end=204
  _globals['_READFILEREQUEST']._serialized_start=206
  _globals['_READFILEREQUEST']._serialized_end=269
  _globals['_READFILECHUNK']._serialized_start=271
  _globals['_READFILECHUNK']._serialized_end=329
  _globals['_WRITEFILECHUNK']._serialized_start=331
  _globals['_WRITEFILECHUNK']._serialized_end=404
  _globals['_WRITEFILERESPONSE']._serialized_start=406
  _globals['_WRITEFILERESPONSE']._serialized_end=448
  _globals['_FILEINFO']._serialized_start=450
  _globals['_FILEINFO']._serialized_end=569
  _globals['_DIRENTRIES']._serialized_start=571
  _globals['_DIRENTRIES']._serialized_end=643
  _globals['_GETPATHRESPONSE']._serialized_start=645
  _globals['_GETPATHRESPONSE']._serialized_end=715
  _globals['_LAZYSYNC']._serialized_start=718
  _globals['_LAZYSYNC']._serialized_end=1044
# @@protoc_insertion_point(module_scope)
