# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lazysync_pb2 as lazysync__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lazysync_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LazySyncStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/lazysync.LazySync/Health',
                request_serializer=lazysync__pb2.HealthRequest.SerializeToString,
                response_deserializer=lazysync__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.GetPath = channel.unary_unary(
                '/lazysync.LazySync/GetPath',
                request_serializer=lazysync__pb2.GetPathRequest.SerializeToString,
                response_deserializer=lazysync__pb2.GetPathResponse.FromString,
                _registered_method=True)
        self.Stat = channel.unary_unary(
                '/lazysync.LazySync/Stat',
                request_serializer=lazysync__pb2.StatRequest.SerializeToString,
                response_deserializer=lazysync__pb2.StatResponse.FromString,
                _registered_method=True)
        self.ReadFile = channel.unary_stream(
                '/lazysync.LazySync/ReadFile',
                request_serializer=lazysync__pb2.ReadFileRequest.SerializeToString,
                response_deserializer=lazysync__pb2.ReadFileChunk.FromString,
                _registered_method=True)
        self.WriteFile = channel.stream_unary(
                '/lazysync.LazySync/WriteFile',
                request_serializer=lazysync__pb2.WriteFileChunk.SerializeToString,
                response_deserializer=lazysync__pb2.WriteFileResponse.FromString,
                _registered_method=True)


class LazySyncServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LazySyncServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=lazysync__pb2.HealthRequest.FromString,
                    response_serializer=lazysync__pb2.HealthResponse.SerializeToString,
            ),
            'GetPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPath,
                    request_deserializer=lazysync__pb2.GetPathRequest.FromString,
                    response_serializer=lazysync__pb2.GetPathResponse.SerializeToString,
            ),
            'Stat': grpc.unary_unary_rpc_method_handler(
                    servicer.Stat,
                    request_deserializer=lazysync__pb2.StatRequest.FromString,
                    response_serializer=lazysync__pb2.StatResponse.SerializeToString,
            ),
            'ReadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadFile,
                    request_deserializer=lazysync__pb2.ReadFileRequest.FromString,
                    response_serializer=lazysync__pb2.ReadFileChunk.SerializeToString,
            ),
            'WriteFile': grpc.stream_unary_rpc_method_handler(
                    servicer.WriteFile,
                    request_deserializer=lazysync__pb2.WriteFileChunk.FromString,
                    response_serializer=lazysync__pb2.WriteFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lazysync.LazySync', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lazysync.LazySync', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LazySync(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lazysync.LazySync/Health',
            lazysync__pb2.HealthRequest.SerializeToString,
            lazysync__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lazysync.LazySync/GetPath',
            lazysync__pb2.GetPathRequest.SerializeToString,
            lazysync__pb2.GetPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lazysync.LazySync/Stat',
            lazysync__pb2.StatRequest.SerializeToString,
            lazysync__pb2.StatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/lazysync.LazySync/ReadFile',
            lazysync__pb2.ReadFileRequest.SerializeToString,
            lazysync__pb2.ReadFileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/lazysync.LazySync/WriteFile',
            lazysync__pb2.WriteFileChunk.SerializeToString,
            lazysync__pb2.WriteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
